from sqlalchemy.sql import text
from SuqeBeEja import engine

productTable = text("""
       CREATE TABLE productTable(
              product_id INT NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
              product_name VARCHAR NOT NULL,
              product_price FLOAT NOT NULL CHECK(product_price > 0),
              product_sub_dep INT NOT NULL,
              amount INT NOT NULL CHECK(amount > 0),
              seller INT NOT NULL,
              brand VARCHAR NOT NULL,
              manufacturer VARCHAR NOT NULL,
              length FLOAT NOT NULL CHECK(length >= 0.0),
              width FLOAT NOT NULL CHECK(width >= 0.0),
              height FLOAT NOT NULL CHECK(height >= 0.0),
              weight FLOAT NOT NULL CHECK(weight >= 0.0),
              date_published DATE NOT NULL,
              condition VARCHAR(3) NOT NULL CHECK (condition in ('NEW', 'OLD')),
              is_featured VARCHAR NOT NULL CHECK(is_featured in ('not', 'day', 'weekly')),
              feature VARCHAR NOT NULL,
              description VARCHAR NOT NULL,
              FOREIGN KEY (seller) REFERENCES sellerTable(seller_id),
              FOREIGN KEY (product_sub_dep) REFERENCES subDepartmentTable(sud_dep_id)
       )
""")  # change is_featured into yes or no

customerTable = text("""
       CREATE TABLE customerTable(
              customer_id INT NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
              customer_name VARCHAR NOT NULL,
              customer_phone_number INT NOT NULL UNIQUE,
              customer_email VARCHAR NOT NULL UNIQUE,
              customer_region VARCHAR NOT NULL,
              customer_city VARCHAR NOT NULL,
              customer_street_number VARCHAR NOT NULL,
              customer_password VARCHAR NOT NULL
       )
""")

sellerTable = text("""
       CREATE TABLE sellerTable(
              seller_id INT NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
              seller_name VARCHAR NOT NULL,
              company_name VARCHAR NOT NULL,
              seller_region VARCHAR NOT NULL,
              seller_city VARCHAR NOT NULL,
              seller_street_number VARCHAR NOT NULL,
              seller_phone_number INT NOT NULL UNIQUE,
              seller_email VARCHAR NOT NULL UNIQUE,
              seller_password VARCHAR NOT NULL
       )
""")

departmentTable = text("""
       CREATE TABLE departmentTable(
              dep_id INT NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
              department_name VARCHAR NOT NULL UNIQUE
       )
""")

subDepartmentTable = text("""
       CREATE TABLE subDepartmentTable(
              sud_dep_id INT NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
              sub_dep_name VARCHAR NOT NULL,
              department_id INT NOT NULL,
              FOREIGN KEY (department_id) REFERENCES departmentTable(dep_id)
       )
""")

imageTable = text("""
       CREATE TABLE imageTable(
              image_id INT NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
              product_id INT NOT NULL,
              image_location VARCHAR NOT NULL,
              lg_image_location VARCHAR NOT NULL,
              FOREIGN KEY (product_id) REFERENCES productTable(product_id)
       )
""")

productReviewTable = text("""
       CREATE TABLE productReviewTable (
              review_id INT NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
              product_id INT NOT NULL,
              comment VARCHAR,
              rating INT NOT NULL CHECK(rating in (0, 1, 2, 3, 4, 5)),
              review_by INT NOT NULL,
              FOREIGN KEY (review_by) REFERENCES customerTable(customer_id),
              FOREIGN KEY (product_id) REFERENCES productTable(product_id)
       )
""")

sellerReviewTable = text("""
       CREATE TABLE sellerReviewTable (
              review_id INT NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
              seller_id INT NOT NULL,
              comment VARCHAR,
              rating INT NOT NULL CHECK(rating in (0, 1, 2, 3, 4, 5)),
              review_by INT NOT NULL,
              FOREIGN KEY (review_by) REFERENCES customerTable(customer_id),
              FOREIGN KEY (seller_id) REFERENCES sellerTable(seller_id)
       )
""")

orderTable = text("""
       CREATE TABLE orderTable(
              order_id INT NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
              product_id INT NOT NULL,
              customer_id INT NOT NULL,
              amount INT NOT NULL DEFAULT 1,
              paid char CHECK (paid in ('y', 'n')),
              FOREIGN KEY (product_id) REFERENCES productTable(product_id),
              FOREIGN KEY (customer_id) REFERENCES customerTable(customer_id)
       )
""")


with engine.connect() as con:
    con.execute(customerTable)
    con.execute(sellerTable)
    con.execute(departmentTable)
    con.execute(subDepartmentTable)
    con.execute(productTable)
    con.execute(imageTable)
    con.execute(orderTable)
    con.execute(productReviewTable)
    con.execute(sellerReviewTable)
